spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#       native:
#       search-locations: "classpath:/config"
        git:
          uri: https://github.com/sohag-aust/microservice-config-properties.git
          default-label: master # branch name for reading config
          timeout: 5 # 5 seconds, my config server has 5 seconds time to read config from the github repository
          clone-on-start: true
          force-pull: true

  # RabbitMQ config for Spring Cloud Bus
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

encrypt:
  key: "this_is_a_random_encrypt_key"

server:
  port: 8071


# Actuator properties
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS