spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#       native:
#       search-locations: "classpath:/config"
        git:
          uri: https://github.com/sohag-aust/microservice-config-properties.git
          default-label: config-for-config-server-in-proxy-test # branch name for reading config
          timeout: 0 # 5 seconds, my config server has 5 seconds time to read config from the github repository
          clone-on-start: true
          force-pull: true

server:
  port: 8071